name: booki
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  carousel_slider: null
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  lottie: ^3.3.1
  pinput: ^5.0.1
  shared_preferences: ^2.5.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets\fonts\DMSerifDisplay-Regular.ttf
